package enums;

public enum configProperties {

    OVERRIDEREPORTS,
    EXCELPATH,
    EXPECTEDRESPONSETIME,
    RETRYCOUNTOFFAILEDTC,
    REGISTRATIONURL,
    REGISTRATIONSHEETNAME,
    LOGINURL,
    LOGINSHEETNAME,
    STEPUPURL,
    STEPUPSHEETNAME,
    AUTHCRITERIACHECKURL,
    AUTHCRITERIACHECKSHEETNAME,
    PERFORMACTIVITYURL,
    PERFORMACTIVITYSHEETNAME,
    PASSEDSTPESSCREENSHOTS,
    FAILEDSTEPSSCREENSHOTS,
    SKIPPEDSTEPSSCREENSHOTS;
}